# Generated by Django 4.0.4 on 2022-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
